apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sitecore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
          kubernetes.io/os: linux
      containers:
      - name: web
        image: nextjsdemoacr.azurecr.io/codewithamitjeedemonextjsapp_web:25
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        env:
          - name: "REACT_APP_ENVIRONMENT"
            value: "Dev"
          - name: "SITECORE_API_KEY"
            value: "546FB77C-D7A2-4B5F-B695-B5355150FCA5"
          - name: "SITECORE_API_HOST"
            value: "https://mccc2memsekrdmx8jw9-cm.managedcloud.sitecore.com/"
          - name: "FETCH_WITH"
            value: "REST"
          - name: "JSS_EDITING_SECRET"
            value: "X0v32AxjP9uFpuR2CSX2eruIdnx0kKY32woGFDyKKd6Z643xeJv6uuXdaURUHZz5"
          - name: "NEXTJS_DIST_DIR"
            value: ".next"
      imagePullSecrets:
        - name: mccc2memsekrdmx8jw9acr