apiVersion: v1
kind: Service
metadata:
  name: renderingjss
spec:
  type: LoadBalancer
  selector:
    app: renderingjss
  ports:
    - name: renderingjss
      port: 80
      protocol: TCP
      targetPort: 3000